import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import { writeAudit } from "@/lib/audit";
const schema=z.object({workOrderId:z.string().min(1),tipoFacturacion:z.enum(["A","N"]),puntoVenta:z.coerce.number().int().positive().optional()});
function canInvoice(user:NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>) {return user.role==="ADMIN"||user.role==="ADMINISTRACION"||user.userRoles.some(ur=>ur.role.active&&ur.role.permissions.some(rp=>rp.permission.key==="invoices.create"));}
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Sesión requerida"},{status:401});try{return NextResponse.json({data:await prisma.invoice.findMany({include:{client:true,workOrder:true,items:true},orderBy:{createdAt:"desc"}})})}catch{return NextResponse.json({error:"No se pudieron cargar las facturas"},{status:500})}}
export async function POST(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Sesión requerida"},{status:401});if(!canInvoice(user))return NextResponse.json({error:"No tenés permiso para facturar"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Datos de factura inválidos"},{status:400});try{const order=await prisma.workOrder.findUnique({where:{id:parsed.data.workOrderId},include:{quote:{include:{items:true}},client:true,deliveries:true,invoices:true}});if(!order)return NextResponse.json({error:"OT inexistente"},{status:404});if(order.deliveries.length===0)return NextResponse.json({error:"Primero confirmá un remito para esta OT"},{status:409});if(order.invoices.length>0)return NextResponse.json({error:"Esta OT ya tiene una factura emitida"},{status:409});const previous=await prisma.invoice.count();const settings=await prisma.companySettings.findFirst();const isA=parsed.data.tipoFacturacion==="A";const total=Number(order.quote.total);const invoice=await prisma.$transaction(async tx=>{const created=await tx.invoice.create({data:{numero:`${isA?"FA":"FN"}-${String(previous+1).padStart(6,"0")}`,tipoFacturacion:parsed.data.tipoFacturacion,arcaVoucherType:isA?"FACTURA_A":null,clientId:order.clientId,workOrderId:order.id,cuit:order.client.cuit,condicionIva:order.client.condicionIva,puntoVenta:parsed.data.puntoVenta??settings?.arcaPuntoVenta??settings?.puntoVentaDefault??1,subtotal:order.quote.subtotalNeto,iva:order.quote.iva,total:order.quote.total,estadoArca:isA?"PENDIENTE":"NO_APLICA",items:{create:order.quote.items.map(item=>({descripcion:item.productoNombre,cantidad:item.cantidad,precioUnitario:item.precioM2Snapshot,subtotal:item.subtotalNeto}))}}});if(isA)await tx.arcaTransaction.create({data:{invoiceId:created.id,idempotencyKey:`arca-${created.id}`,environment:settings?.arcaEnvironment??"HOMOLOGACION",requestPayload:{reason:"Pendiente de credenciales de homologación"},resultado:"PENDIENTE"}});const balances=await tx.accountMovement.aggregate({where:{clientId:order.clientId},_sum:{debe:true,haber:true}});await tx.accountMovement.create({data:{clientId:order.clientId,tipo:"FACTURA",referencia:created.numero,debe:total,haber:0,saldo:Number(balances._sum.debe??0)-Number(balances._sum.haber??0)+total}});await tx.workOrder.update({where:{id:order.id},data:{estadoFacturacion:"FACTURADA"}});return created});await writeAudit(user.id,"EMITIR","Invoice",invoice.id,undefined,{numero:invoice.numero,tipo:invoice.tipoFacturacion});return NextResponse.json({data:invoice},{status:201})}catch(error){console.error("[invoices]",error);return NextResponse.json({error:"No se pudo emitir la factura"},{status:500})}}
