"use client";
import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Input, Label } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default function PerfilPage() {
  const [user, setUser] = useState<any>(null); const [currentPassword, setCurrentPassword] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/auth/me").then((r) => r.json()).then((d) => setUser(d.user)); }, []);
  async function updatePassword() { setSaving(true); setError(""); setMessage(""); const response = await fetch("/api/profile/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword: password }) }); const body = await response.json().catch(() => null); setSaving(false); if (!response.ok) return setError(body?.error ?? "No se pudo actualizar la contraseña."); setCurrentPassword(""); setPassword(""); setMessage("Contraseña actualizada correctamente."); }
  return <div className="max-w-2xl space-y-6"><div><h1 className="text-xl font-bold">Mi perfil</h1><p className="text-sm text-muted-foreground">Tus datos y acceso al sistema.</p></div><Card className="space-y-4 p-5"><div><Label>Nombre</Label><p className="text-sm font-medium">{user?.name ?? "Cargando…"}</p></div><div><Label>Email</Label><p className="text-sm font-medium">{user?.email ?? "Cargando…"}</p></div><div><Label>Roles</Label><p className="text-sm font-medium">{user?.roles?.join(", ") || user?.role || "—"}</p></div></Card><Card className="space-y-4 p-5"><h2 className="font-semibold">Cambiar contraseña</h2><div><Label htmlFor="current-password">Contraseña actual</Label><Input id="current-password" type="password" autoComplete="current-password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></div><div><Label htmlFor="new-password">Nueva contraseña</Label><Input id="new-password" type="password" minLength={8} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} /></div><Button onClick={updatePassword} disabled={saving || currentPassword.length < 1 || password.length < 8}>{saving ? "Actualizando…" : "Actualizar contraseña"}</Button>{message && <p role="status" className="text-sm text-vase-green">{message}</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</Card></div>;
}
