"use client";
import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { Input, Label } from "@/components/ui/input";
import { formatDate } from "@/lib/format";
import { Check, Printer, Receipt, X } from "lucide-react";
export default function RemitosPage() {
 const [notes,setNotes]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[action,setAction]=useState<"confirm"|"cancel"|null>(null),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=()=>fetch("/api/delivery-notes").then(r=>r.ok?r.json():null).then(p=>setNotes(p?.data??[])).catch(()=>setNotes([])); useEffect(()=>{load()},[]);
 async function execute(){if(!selected||!action)return;setBusy(true);setError("");const r=await fetch(`/api/delivery-notes/${selected.id}/${action==="confirm"?"confirm":"cancel"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:action==="cancel"?JSON.stringify({motivo:reason}):undefined});const p=await r.json().catch(()=>null);setBusy(false);if(!r.ok){setError(p?.error??"No se pudo actualizar el remito");return}setAction(null);setSelected(null);setReason("");load()}
 return <div className="space-y-6"><div><h1 className="text-xl font-bold tracking-tight">Remitos</h1><p className="text-sm text-muted-foreground">Confirmá el remito para descontar la entrega y luego generar la factura.</p></div><div className="space-y-3">{notes.map((note)=><Card key={note.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><b>{note.numero}</b><Badge variant={note.estado==="CONFIRMADO"?"success":note.estado==="ANULADO"?"danger":"warning"}>{note.estado}</Badge></div><p className="text-sm text-muted-foreground">{note.client?.razonSocial} · OT {note.workOrder?.numero}</p><p className="text-xs text-muted-foreground">{formatDate(note.fecha)} · {note.direccion}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>window.location.href=`/remitos/${note.id}/imprimir`}><Printer className="h-3.5 w-3.5"/> Imprimir / PDF</Button>{note.estado==="CONFIRMADO"&&<Button size="sm" variant="outline" onClick={()=>window.location.href=`/facturacion?nuevo=${note.workOrderId}`}><Receipt className="h-3.5 w-3.5"/> Generar factura</Button>}{note.estado==="BORRADOR"&&<Button size="sm" onClick={()=>{setSelected(note);setAction("confirm")}}><Check className="h-3.5 w-3.5"/> Confirmar</Button>}{note.estado!=="ANULADO"&&<Button size="sm" variant="outline" onClick={()=>{setSelected(note);setAction("cancel")}}><X className="h-3.5 w-3.5"/> Anular</Button>}</div></div><div className="mt-4 divide-y text-sm">{note.items.map((item:any)=><div key={item.id} className="flex justify-between py-2"><span>{item.productoNombre}</span><b>{item.cantidadEntregada} unidades</b></div>)}</div></Card>)}{notes.length===0&&<Card className="p-10 text-center text-sm text-muted-foreground">No hay remitos creados todavía.</Card>}</div><Modal open={!!action} onClose={()=>setAction(null)} title={action==="confirm"?"Confirmar remito":"Anular remito"} description={action==="confirm"?"La confirmación crea la entrega definitiva.":"La anulación revierte la entrega y requiere un motivo."} footer={<><Button variant="outline" onClick={()=>setAction(null)}>Cancelar</Button><Button disabled={busy||(action==="cancel"&&reason.trim().length<5)} onClick={execute}>{busy?"Procesando…":"Confirmar"}</Button></>}>{action==="cancel"&&<div><Label>Motivo</Label><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Mínimo 5 caracteres"/></div>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</Modal></div>;
}
