import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { hashPassword, requirePermission } from "@/lib/auth";
import { writeAudit } from "@/lib/audit";
import { assertSameOrigin } from "@/lib/security/csrf";
import { assertCrudAllowed, SUPER_ADMIN_ERROR } from "@/lib/user-protection";

const payload = z.object({ id: z.string().optional(), name: z.string().trim().min(2), email: z.string().trim().email(), password: z.string().min(8).optional(), active: z.boolean().optional(), roleIds: z.array(z.string()).min(1) });
const userSelect = { id: true, name: true, email: true, role: true, active: true, isSuperAdmin: true, userRoles: { include: { role: { select: { id: true, name: true, active: true } } } } } as const;
const failure = (error: unknown) => NextResponse.json({ error: error instanceof Error && error.message === "LAST_ADMIN" ? "No podés desactivar al último administrador activo." : error instanceof Error && error.message === "SUPER_ADMIN_PROTECTED" ? SUPER_ADMIN_ERROR : error instanceof z.ZodError ? error.issues[0]?.message : "No se pudo guardar el usuario." }, { status: error instanceof Error && error.message === "SUPER_ADMIN_PROTECTED" ? 403 : 400 });

async function assertRoles(roleIds: string[]) { const roles = await prisma.roleDefinition.findMany({ where: { id: { in: roleIds }, active: true }, select: { id: true } }); if (roles.length !== roleIds.length) throw new Error("INVALID_ROLE"); return roles; }
async function assertAdminRemains(userId: string, active: boolean, roleIds: string[]) { const admin = await prisma.roleDefinition.findUnique({ where: { name: "ADMIN" } }); if (!admin || (active && roleIds.includes(admin.id))) return; const otherAdmins = await prisma.userRole.count({ where: { roleId: admin.id, user: { active: true, id: { not: userId } } } }); if (!otherAdmins) throw new Error("LAST_ADMIN"); }

export async function GET() { try { await requirePermission("users.view"); return NextResponse.json(await prisma.user.findMany({ select: userSelect, orderBy: { name: "asc" } })); } catch (error) { return NextResponse.json({ error: error instanceof Error && error.message === "UNAUTHENTICATED" ? "Sesión requerida" : "No tenés permiso para ver usuarios" }, { status: error instanceof Error && error.message === "UNAUTHENTICATED" ? 401 : 403 }); } }

export async function POST(request: Request) { try { assertSameOrigin(request); const actor = await requirePermission("users.manage"); const input = payload.extend({ password: z.string().min(8) }).parse(await request.json()); const roles = await assertRoles(input.roleIds); const user = await prisma.user.create({ data: { name: input.name, email: input.email.toLowerCase(), passwordHash: hashPassword(input.password), role: "ADMINISTRACION", active: input.active ?? true, userRoles: { create: roles.map((role) => ({ roleId: role.id })) } }, select: userSelect }); await writeAudit(actor.id, "USER_CREATED", "User", user.id, undefined, { name: user.name, roleIds: input.roleIds }); return NextResponse.json(user, { status: 201 }); } catch (error) { return failure(error); } }

export async function PATCH(request: Request) { try { assertSameOrigin(request); const actor = await requirePermission("users.manage"); const input = payload.parse(await request.json()); if (!input.id) return NextResponse.json({ error: "Falta el usuario." }, { status: 400 }); const before = await prisma.user.findUnique({ where: { id: input.id }, select: userSelect }); if (!before) return NextResponse.json({ error: "Usuario inexistente." }, { status: 404 }); assertCrudAllowed(before.isSuperAdmin); await assertAdminRemains(input.id, input.active ?? before.active, input.roleIds); const roles = await assertRoles(input.roleIds); const user = await prisma.$transaction(async (tx) => { if (input.active === false) await tx.session.updateMany({ where: { userId: input.id, revokedAt: null }, data: { revokedAt: new Date() } }); return tx.user.update({ where: { id: input.id }, data: { name: input.name, email: input.email.toLowerCase(), active: input.active ?? before.active, ...(input.password ? { passwordHash: hashPassword(input.password) } : {}), userRoles: { deleteMany: {}, create: roles.map((role) => ({ roleId: role.id })) } }, select: userSelect }); }); const previousRoles = before.userRoles.map((entry) => entry.role.id).sort(); const rolesChanged = previousRoles.join(",") !== [...input.roleIds].sort().join(","); if (rolesChanged) await writeAudit(actor.id, "USER_ROLES_CHANGED", "User", user.id, { roleIds: previousRoles }, { roleIds: input.roleIds }); if (input.password) await writeAudit(actor.id, "USER_PASSWORD_RESET", "User", user.id, undefined, { reset: true }); if (before.active !== user.active) await writeAudit(actor.id, user.active ? "USER_ENABLED" : "USER_DISABLED", "User", user.id, { active: before.active }, { active: user.active }); await writeAudit(actor.id, "USER_UPDATED", "User", user.id, { name: before.name, email: before.email }, { name: user.name, email: user.email }); return NextResponse.json(user); } catch (error) { return failure(error); } }
