"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/format";

export default function WorkOrderDetailPage({ params }: { params: Promise<{ id: string }> }) { const [order, setOrder] = useState<any>(null); const [error, setError] = useState(""); useEffect(() => { params.then(({ id }) => fetch(`/api/work-orders/${id}`).then((r) => r.json()).then((p) => p?.data ? setOrder(p.data) : setError(p?.error ?? "No se pudo cargar la OT."))); }, [params]); if (error) return <Card className="p-6 text-sm text-red-600">{error}</Card>; if (!order) return <p className="p-8 text-sm text-muted-foreground">Cargando OT…</p>; const dvh = order.categoria === "DVH"; return <div className="space-y-6"><Link href="/produccion" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground"><ArrowLeft className="h-3.5 w-3.5" /> Volver a producción</Link><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">Orden de trabajo · {dvh ? "DVH" : order.categoria}</p><h1 className="text-2xl font-bold">{order.numero}</h1><p className="text-sm text-muted-foreground">{order.client.razonSocial} · {order.obra || "Sin obra"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/ordenes-trabajo/${order.id}/imprimir?sector=CORTE`}><Button variant="outline"><Printer className="h-4 w-4" /> Imprimir Corte / PDF</Button></Link>{dvh && <Link href={`/ordenes-trabajo/${order.id}/imprimir?sector=ARMADO`}><Button variant="outline"><Printer className="h-4 w-4" /> Imprimir Armado / PDF</Button></Link>}</div></div><Card className="p-5"><div className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Field label="Presupuesto" value={`${order.quote.numero}${order.quote.titulo ? ` · ${order.quote.titulo}` : ""}`} /><Field label="Entrega prevista" value={formatDate(order.fechaEntrega)} /><Field label="Prioridad" value={order.prioridad} /><Field label="Estado" value={order.estadoProductivo} /></div></Card>{dvh && <div className="grid gap-4 md:grid-cols-2"><DvhSector title="CORTE" assigned={order.corteUsuario?.name} items={order.quote.items} /><DvhSector title="ARMADO" assigned={order.armadoUsuario?.name} items={order.quote.items} /></div>}{!dvh && <DvhSector title="PRODUCCIÓN" assigned={order.corteUsuario?.name} items={order.items} />}</div>; }
function Field({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value}</p></div>; }
function DvhSector({ title, assigned, items }: { title: string; assigned?: string; items: any[] }) { return <Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">{title}</h2><p className="text-xs text-muted-foreground">{assigned ? `Asignado a ${assigned}` : "Sin asignar"}</p></div><span className="rounded-full bg-vase-green-soft px-2.5 py-1 text-xs font-semibold text-vase-green-dark">{items.reduce((sum, item) => sum + item.cantidad, 0)} DVH</span></div><div className="mt-4 space-y-3">{items.map((item: any, index: number) => { const d = item.dvhDetail; return <div key={item.id ?? index} className="rounded-xl border border-border p-3 text-sm"><p className="font-semibold">{d?.composicion || item.productoNombre}</p><p className="mt-1 text-xs text-muted-foreground">{item.anchoMm} × {item.altoMm} mm · {item.cantidad} unidades</p>{d ? <div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><p><b>Vidrio exterior:</b> {d.vidrioExteriorTipo} · {d.vidrioExteriorEspesorMm} mm</p><p><b>Vidrio interior:</b> {d.vidrioInteriorTipo} · {d.vidrioInteriorEspesorMm} mm</p><p><b>Cámara:</b> {d.camara}</p><p><b>Separador:</b> {d.separador}</p><p><b>Sellado:</b> {d.sellado}</p><p><b>Corte:</b> {item.cantidad} exterior + {item.cantidad} interior</p></div> : <p className="mt-2 text-xs text-muted-foreground">Detalle productivo de la OT</p>}</div>; })}</div></Card>; }
